sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: blurb
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - removeformat
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: Blurb
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: retail_pricing
        field:
          input_type: text
          antlers: false
          display: 'Retail pricing'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: brochure
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Brochure
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: images
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: Images
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: description
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: Description
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: features_specs
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: Features/specs
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: reviews
        field:
          collapse: false
          sets:
            review:
              display: Review
              fields:
                -
                  handle: review_text
                  field:
                    antlers: false
                    display: 'Review text'
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    read_only: false
                -
                  handle: review_attribution
                  field:
                    input_type: text
                    antlers: false
                    display: 'Review Attribution'
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                    read_only: false
          display: Reviews
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: brands
        field:
          type: terms
          taxonomies:
            - brands
          display: Brand
          mode: select
          instructions_position: above
          listable: hidden
          read_only: false
          max_items: 1
          create: true
title: Products
