title: Products
template: product
layout: layout
taxonomies:
  - brands
  - product_type
  - featured
revisions: false
route: 'brands/{brands}/{title}'
sort_dir: asc
date_behavior:
  past: public
  future: private
