title: 'Audio Analogue'
hero_image: adwasdwaws-scaled.jpg
byline: 'Sound Pleasure'
blurb:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Audio Analogue was born in the beautiful corner of Tuscany between Pistoia, Lucca and Pisa in 1995. The synergy between high-end audio experts, electronic engineers specialized in the most different fields of electronic design and commercial managers with many years of experience in different fields could only create the basis of what is Audio Analogue today: a company but above all one of the most popular brands in Italy and in the World able to satisfy the tastes of the most demanding audiophiles.'
      -
        type: hard_break
      -
        type: text
        text: 'Products always fully MADE IN ITALY, in the heart, soul and substance, using mainly small and very qualified local industries and artisans to make the most of Italian excellence and grow the quality of our and their work. Devices completely hand-crafted, tested with first-class instrumentation, but also and above all with listening tests, always rediscovering the emotion of having created something that can in turn give emotions through listening to the favorite music.'
logo: download-(1).jpg
updated_by: bf123438-d04c-4a45-b0fa-3e0cea9cbedd
updated_at: 1657653333
blueprint: brands
