title: Einstein3
blurb:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Blurb for Einstein goes here'
updated_by: 9689cde4-d9c4-4a0a-a0f0-e088ff46ca01
updated_at: 1656541868
blueprint: brands
hero_image: einstein.jpeg
byline: 'Handcrafted German audio excellence since 1988'
