title: Einstein
blurb:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Blurb for Einstein goes here'
updated_by: 9689cde4-d9c4-4a0a-a0f0-e088ff46ca01
updated_at: 1654463305
blueprint: brands
