title: Heretic
logo: hereric-sept-2022-metal.png
makers_of:
  - speakers
updated_by: 9689cde4-d9c4-4a0a-a0f0-e088ff46ca01
updated_at: 1689734196
blueprint: brands
hero_image: heretic-speaker-living-retro-a7-1-1.jpg
byline: 'Driven by Technology. Passionate for Sound.'
blurb:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'The Heretic A614 Speakers: A perfect blend of new and legacy'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: italic
        text: 'By Jeff Dorgay'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Warning, these speakers tend to keep you cemented in your listening chair. The Heretics are “album side” speakers if that makes sense.'
  -
    type: paragraph
    content:
      -
        type: text
        text: "Spinning Nightmares on Wax’s\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "In A Space Outta Sound,\_"
      -
        type: text
        text: "the dub heavy, trippy vibe is intoxicating. Next up, Propellerheads\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "Decksanddrumsandrockandroll.\_"
      -
        type: text
        text: 'Again, the whole album goes by without the slightest urge to make a playlist. The bass line in “Oh Yeah?” is so much fun. The 12” coaxial driver combined with the ported cabinet adds up to a very organic, tuneful (yet not overdamped) bottom end.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'If you’ve looked at Heretic’s website (www.thehereticspeaker.com) you’ll notice the famous shot of EMI studios, with the Beatles in the control room. They are listening to what looks like the larger Heretic A612, but these are actually Altec drivers in the cabinets. Robert Gaboury, the man behind the Heretic has taken this 12” coax and the Altec cabinet design and brought it into the modern age, to produce a speaker that is really a pleasure to listen to.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Powered by the Lab12 Mighty amplifier, which only produces 10 watts per channel, these speakers sporting a 97db/1-Watt sensitivity rating barely make the cool, circular VU meters move from rest. Seriously, how often do most of you listen to music at a 97db level? It’s unbelievable that this pair of speakers, combined with a $2,400 power amplifier can create such an expansive and immersive musical experience. But it does. Pricing is TBA right now, but they will be under $8k/pair for the smaller 614s, reviewed here.'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Quick, adjective barrage'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'All of those audiophile cliches we’ve heard a million times over truly do apply to the Heretic A614s, but they are one of those rare speakers that provide instant fun. If you’re a persnickity audiophile, you’ll find things to nitpick, but then you will no matter what you’re listening to. These won’t be the speakers for you.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'You can look at these speakers one of two ways – you can be fussy and point out the small things they don’t do (as you would with every single other speaker made) or you can sink into the vibe and just enjoy them. To give you a reference point of where I’m coming from (because saying a speaker is “fun,” really doesn’t give you much to go on…) my short list of fun, under $10k/pair speakers are in no order, The Vandersteen 1C, The JBL L-100 Century Classic, The Magnepan SMG, A nice used pair of MartinLogan CLS’s, The Harbeth C7s, The Zu Dirty Weekends.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Speakers that are not necessarily the last word in audiophile speakers, but ones that you can sit around all evening listening to music with, have a great time, and not have to engage the audiophile part of your consciousness that feels the need to dissect everything.'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Quick setup'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Thanks to their relatively light weight – about 40 pounds each, with a profile of 19” wide, 15” deep, and about 26” tall, you can move the Heretics around and set them up easily by yourself.'
      -
        type: hard_break
      -
        type: text
        text: 'Having used these in small (10 x 13 foot), medium (11 x 18 foot) and large (15 x 26 foot) the Heretics deliver great results anywhere, though you will get a little bit more bass loading in an extremely small room, that may or may not work to your advantage.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'While these speakers come with feet attached for use on the floor, I had the best results getting them about 13” off the floor. Custom stands are on the way, but for now a pair of heavy Sound Anchors stands with 1.25 thick butcher block boards work splendidly. A little blu tack between the boards and the stands really helps too. Getting that tweeter up a little higher than ground level makes for a lot less mid-bass bloom/roundness and gives up nothing on the bottom end. This also helps the Heretics to create a larger soundstage, eliminating a lot of reflection right from the floor.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Because the originals have that EMI heritage, the push for some Beatle’s was just too much to resist, and considering it’s that time of the year here in America again, Revolvers’ “Taxman” was perfect. These speakers do such a great job at holding the bass line rock solid, the drums in place and a clear view of all the harmonies – it’s incredible. And incredibly enjoyable. Whether you prefer the stereo or mono Beatles, this is a treat. Switching it up for Cheap Trick’s “Taxman, Mr. Thief” is equally rewarding. And this is not an awesome recording by any stretch. Yet the slightly round bottom end of these speakers gives a little bit of help to the average recordings in your collection. Again, that fun thing.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'For those of you that haven’t been following my ongoing narrative, one of my biggest hot buttons is coherence. Thanks to the coaxial tweeter, these speakers sound like a big single driver speaker with extension. The crossovers are well designed, as the transition from woofer to tweeter is as good as it gets – seamless and free of grain. Regardless of what kind of music you enjoy, these speakers do a fantastic job rendering it.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Vocals are transcendent with the Heretics, both in terms of tonality and the way they can decode layered harmonies. The Heretics are highly natural in their presentation, and again thanks to the high sensitivity, nothing is ever working hard to produce sound – resulting in low distortion and fatigue. These are speakers you can listen to all day without becoming the least bit tired.'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: Amplification
  -
    type: paragraph
    content:
      -
        type: text
        text: "Don’t let the sensitivity rating fool you, even though these speakers don’t need a tremendous amount of power to play\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "really loud,\_"
      -
        type: text
        text: 'it’s a quality thing. A few obvious choices (the Cary 805 SET monos, the Line Magnetic 815) didn’t provide killer results, yet the 4 watt per channel Finale is out of this world good. As mentioned at the beginning of this review, Lab12s Mighty (10 watts per channel) is also fantastic. Our Pass First Watt SIT-3 was also a stunner. This amplifier is very speaker sensitive, but in this case, the match is perfection. This single ended solid-state amplifier delivers about 92% of the texture and depth of the best tube combinations, with a bigger image, and a lot more slam on the low end. So, again – big fun with these speakers. And there’s still about five or six amplifiers to try.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Perhaps we were cheating a bit at first, using the Pass XS Pre, XS Phono and dCS Vivaldi One with Vivaldi Clock, but even when bringing the associated components downstream in keeping with you’d probably expect to be in a system with a pair of speakers in this price range, the results are still excellent. The only thing tried that was less than awesome was our vintage Marantz 2270. This just sounded flat.'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'The rest of the story'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Looking at the Heretic site, you’ll see there are several other finishes available, and you can order the speakers with or without grilles. If you have munchkins or pets, seriously consider the grilles. Our review pair came in the natural finish.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Gaboury says that the cabinets are made from 12mm Canadian ultra-premium birch plywood. The website says, “Because of tone. Tone comes from rigidity, lightness, and compliance, but not too much.” Rather than go on and on, if there is any way you can give these speakers a listen, if you share some of my listening priorities, I think you will really enjoy the Heretics. Should you have a larger room, or need more bass extension, they also make the A612, which is the same driver in a cabinet with more volume.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Sensitivity remains the same, but there is an additional half octave of bass extension. When Mr. Gaboury catches up with orders, he’s promising to send us a pair. For now, provisionally, I am purchasing the review pair, but I may hold the checkbook close to the vest until I hear the bigger model. I’ve got the room. Either way, these speakers have provided some of the most fun I’ve had in a long time just hanging out and listening to music for its own sake. You’ll only need one or two of your favorite tracks to decide if they are the droids you want.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'For now, highly recommended, and #toneaudioapproved.'
